In [1]:
from numpy import *
# import matplotlib

In [2]:
a = array([2,3,4])

In [3]:
print(a)
a

[2 3 4]


array([2, 3, 4])

In [4]:
a.ndim   # размерность массива

1

In [11]:
a.shape 

(3,)

In [5]:
b = array([(1.5, 2, 3), (4, 5, 6)])

In [13]:
b

array([[ 1.5,  2. ,  3. ],
       [ 4. ,  5. ,  6. ]])

In [14]:
b.ndim

2

In [15]:
b.shape

(2, 3)

In [16]:
b.size

6

In [17]:
z = zeros((3,2)) # 3, 2 помещаются в дополнительные скобки, чтобы представлять из себя один объект

In [18]:
z

array([[ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.]])

In [19]:
arange(10, 30, 5) #функция arange аналогична функции range, но возвращает массив

array([10, 15, 20, 25])

In [20]:
linspace(0, 2, 9) # генерирует 9 чисел на отрезке от 0 до 2 с равным шагом

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ,  1.25,  1.5 ,  1.75,  2.  ])

In [24]:
b = arange(12).reshape(4, 3)
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [25]:
a = array([10, 20, 30])
b = arange(3)
print(a)
print(b)

[10 20 30]
[0 1 2]


In [27]:
print(a+b)
print(a-b)

[10 21 32]
[10 19 28]


In [29]:
print(a**2)

[100 400 900]


In [30]:
a * sin(a)

array([ -5.44021111,  18.25890501, -29.64094872])

In [31]:
a<20

array([ True, False, False], dtype=bool)