In [ ]:
1.3.1

In [4]:
x = [1, 2]

print(list(map(lambda c: c % 2, x)))

[1, 0]


In [5]:
print(map(lambda c: c % 2, x))

In [ ]:
1.3.2 Напишите формулу для производной по x функции 3x**2−sin(2x)logy. Переменные x и y не зависят друг от друга. 

3x**2' = 6x
sin(2x)' = 2 cos 2x
logy' = 1/y

6 * x - 2 * cos (2*x) * log(y) # правильный ответ

In [ ]:
6 * x - 2 * cos (2*x) * log(y) - sin(2 * x) / y  # неправильный ответ, т.к. требовалась производная по X

1.3.3 Чему равна производная функции ((ax+b) / (cx+d))' по x?

(U / V)' = (U'V -V'U) / V**2

In [ ]:
(ad - bc) / (cx + d)**2

In [ ]:
1.3.4 Чему равна производная функции ((ax+b) / (cx+d))' по c?



In [ ]:
- x(ax+b) / (cx + d)**2

In [ ]:
1.3.5 Чему равна производная функции 1 / 4 Ln ((x**2 - 1)/(x**2 + 1)) в точке x = 3

In [ ]:
logy' = 1/y

In [6]:
x = 3
y = 1 / 4 * ((x**2 + 1) / (x**2 - 1))
print(y)

0.3125


In [ ]:
0.0375

In [ ]:
1.3.6 Задача "опять 25". Мы не будем заниматься арифметикой, но нам нужно проверить, что вы помните свойства степеней =)

Найдите, чему равно ((5**2)**(5**3)*50**100)/(100**50*(5**3)**(5**2)*25**137)

In [7]:
((5**2)**(5**3)*50**100)/(100**50*(5**3)**(5**2)*25**137)

5.0

1.3.7 Найдите значение (Log2(8) + Log2(18))/(2log2(2) + log2(3))


$$ \frac{Log_{2}8 + Log_{2}18}{2log_{2}2 + log_{2}3} $$

1)  $$ Log_{a}b + Log_{a}c=Log_{a}(b*c)  $$

2) $$ nLog_{a}(b) = Log_{a}(b^n) $$

3) $$ \frac{Log_{c}a}{Log_{c}b} = Log_{b}a $$

$$ \large Log_{a^k}a = \frac{1}{k} $$

In [9]:
(3 + 18**0.5) / (2 + 3**0.5)

1.940659723182404

In [ ]:
2

1.3.8 Найдите значение $$ Log_{225}20 * Log_{289}15 * Log_{20}17 $$

$$ Log_{225}20 * Log_{289}15 * Log_{20}17  = Log_{225}15 * Log_{289}17 * Log_{20}20 = \frac{1}{2} * \frac{1}{2} * 1 = \frac{1}{4} $$

1.3.8 Найдите точку локального максимума функции

$$ f(x,y) = x^3 + 4y^3 - 3x - 3y $$

Запишите ответ в виде двух чисел (координата по x, координата по y) в десятичном формате через запятую, отделяя целую часть от дробной точкой (например,
2.5, -3
, если вы считаете, что 

$$ max{f(x,y)|x,y ∈ \mathbb {R}} = f(2.5,−3)). $$

In [ ]:
-1, -0.5

1.3.9 Укажите, какие из предложенных операций можно осуществить для матриц A размера 3×4, B размера 3×6 и C размера 4×6.

In [ ]:
1) размерности при умножении ведут себя так: [n x m]*[m x k]=[n x k]
2)при суммировании размерность не меняется и суммировать можно только одинаковые по размерностям матрицы

[n x m]+[ n x m ]=[ n x m ] 

## Линейная алгебра

### Вектор
1. умножение на константу
2. Сложение векторов 
3. Вычитание векторов
4. Взятие длины вектора
5. Скалярное произведение
6. Векторное произведение

Вектор - это набор из нескольких чисел, записанных в столбик и заключенных в круглые или квадратные скобки.

$$ v = \left[ 
    \begin{array}{ccc}
    e_{1} \\ 
    e_{2}  \\
    ..  \\
    e_{n} \\
    \end{array}
\right] $$

Размерность вектора - количество элементов в данном наборе. Для вектора $v$ это будет $n$. Размерность вектора это натуральное число. Элементы вектора могут быть любого типа.

#### умножение на константу




$$ a = 
\left[ 
    \begin{array}{ccc}
    x_{1} \\ 
    x_{2}  \\
    ..  \\
    x_{n} \\
    \end{array}
\right] 
b = 
\left[ 
    \begin{array}{ccc}
    y_{1} \\ 
    y_{2}  \\
    ..  \\
    y_{n} \\
    \end{array}
\right]  
$$

пусть есть константа $c$, тогда произведение вектора $a$ и константы $c$ будет равно новому вектору, в котором каждый элемент просто домножен на $c$.

$ a \cdot c = 
\left[ 
    \begin{array}{ccc}
    x_{1}c \\ 
    x_{2}c  \\
    ..  \\
    x_{n}c \\
    \end{array}
\right]
$

In [ ]:
#### сложение векторов

Если размерности двух векторов совпадают, то мы можем рассмотреть их суммму

$ a + b = 
\left[ 
    \begin{array}{ccc}
    x_{1} + y_{1} \\ 
    x_{2} + y_{2} \\
    ..  \\
    x_{n} + y_{n} \\
    \end{array}
\right]
$

#### разность векторов

$a - b = \left[ 
    \begin{array}{ccc}
    x_{1}-y_{1} \\ 
    x_{2}-y_{2} \\
    ..  \\
    x_{n}-y_{n} \\
    \end{array}
\right]$

#### взятие длины вектора

Длиной вектора называется число равное корню суммы квадратов всех его элементов

$|a| = \sqrt{x_{1}^2 + x_{2}^2 + .. + x_{n}^2}$

#### скалярное произведение 

скалярное произведение двух векторов равно сумме попарных произведений соответвующих (имеющих одинаковый индекс) элементов.

$a \cdot b = x_{1}y_{1} + x_{2}y_{2} + .. x_{n}y_{n} = |a|\cdot|b|\cdot cos \alpha$

#### векторное произведение 

$ a\times b$

1.4.4

## Геометрический смысл векторов
1. Свободные векторы
2. Скользящие векторы
3. Связанные (фиксированные) векторы

Вектор - это направленный отрезок. 
Угол между двумя векторами - это минимальный угол, на который нужно повернуть один из них, чтобы он совпал с другим.





#### Скалярное произведение
опустим перпендикуляр из вектора A на прямую на которой лежит вектор B. Между ними угол $\varphi$. Отрезок до перпендикуляра $a$.

$A\cdot B = |A|\cdot|B|\cdot cos \varphi \\
cos\varphi = \frac{a}{|A|} \\
cos\varphi \cdot |A| = a
$

Т.е. $cos\varphi \cdot |A|$ равен проекции вектора A на вектор B. 

Скалярное произведение векторов A и B это длина проекции первого вектора на второй, масштабированная на длину второго вектора. Это верно для n-мерного пространства.

$$ \frac{A \cdot B}{|A| \cdot |B|} $$

$A \cdot B$ это скалярное прозведение (равно сумме попарно умноженных соответствующих координат), $|A|\cdot|B|$ это произведение длин векторов. Это равно косинусу угла между ними.

$$ \frac{A \cdot B}{|A| \cdot |B|} = cos\varphi$$

Зная косинус, можно узнать про угол между ними. Можно просто взять arccos от этого выражения и узнать угол между векторами. Данный факт имеет приложение в анализе данных, сигналов.

## 1.5 Матрицы
Матрица это прямоугольный набор чисел, записанный между квадратными или круглыми скобками.

$\left[ 
    \begin{array}{ccc}
    a_{11}..a_{1m} \\ 
    a_{21}..a_{2m} \\
    ..  \\
    a_{n1}..a_{nm} \\
    \end{array}
\right]$

Элемент $a_{ij}$ находится в i строке, j столбце. Запись $B_{n\times m}$ означает, что у матрицы B n рядов и m столбцов

### Векторы как одномерные матрицы
Вектор - это частный случай матрицы.
Существуют вектор-столбцы и вектор-строки.

### Операции над матрицами
#### сложение матриц
    Если у двух матриц совпадают размерности, то их можно сложить. Сумма двух матриц имеет ту же размерность, что и исходные матрицы. Элементы попозиционно складываются.

#### умножение на число
Каждый элемент матрицы умножается на это число.

#### произведение матриц
Чтобы матрицы A И B можно было перемножить, количество столбцов первой матрицы должно совпадать с количеством рядов второй. При этом получится матрица C размерности 

## NumPy Основы

In [1]:
import numpy as np

In [2]:
a = np.array([[1,2,3], [4,5,6]])  # создаём массив
print(a)  # смотрим на массив



[[1 2 3]
 [4 5 6]]


In [3]:
a.shape  # смотрим на форму массива


(2, 3)

- array(object) — n-мерный массив из любой (возможно, вложенной) последовательности,
- eye(N, M=N, k=0) -- двумерный массив с N строками с единицами на диагонали и нулями во всех остальных позициях. Число столбцов M по умолчанию равно N, k — сдвиг диагонали (0 для основной диагонали, положительные числа для верхних диагоналей и отрицательные для нижних),
- zeros(shape) -- новый массив указанной формы, заполненный нулями,
- ones(shape) -- новый массив указанной формы, заполненный единицами,
- full(shape, fill_value) -- новый массив указанной формы, заполненный fill_value.

In [8]:
np.eye(4, 5, -1)

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [20]:
np.zeros([3,4] )

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [19]:
np.ones([2, 4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [21]:
np.full([2,3], 8)

array([[8, 8, 8],
       [8, 8, 8]])

In [22]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
a[1,::2,]

array([4, 6])

In [33]:
a[..., 1]

array([2, 5])

In [34]:
a[:, 1]

array([2, 5])

In [ ]:
#### 1.6.5 
Создайте и напечатайте (с помощью функции print) массив класса np.ndarray ширины 4 и высоты 3 с двойками на главной диагонали и единицами на первой диагонали над главной, т.е. воплощение матрицы

⎛⎝⎜200120012001⎞⎠⎟
Обратите внимание на то, что мы используем Python 3, где print() принимает аргументы в скобках.

Подсказка: простым путём может быть использование сложения и умножения на константу.

In [12]:
a = np.eye(3,4, dtype=int)
a

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0]])

In [13]:
b = np.eye(3, 4, 1, dtype=int)
b

array([[0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [45]:
print(a + 2*b)

[[1 2 0 0]
 [0 1 2 0]
 [0 0 1 2]]


In [14]:
a = np.eye(3,4, dtype=int)
b = np.eye(3, 4, 1, dtype=int)
print(2*a + b)

[[2 1 0 0]
 [0 2 1 0]
 [0 0 2 1]]


In [16]:
a = (2*a + b)

In [17]:
a.flatten()

array([2, 1, 0, 0, 0, 2, 1, 0, 0, 0, 2, 1])

In [57]:
a.T

array([[2, 0, 0],
       [1, 2, 0],
       [0, 1, 2],
       [0, 0, 1]])

In [ ]:
a.transpose(*axes)

In [52]:
a.reshape([2,6])

array([[2, 1, 0, 0, 0, 2],
       [1, 0, 0, 0, 2, 1]])

In [19]:
import random
w = np.array(random.sample(range(1000), 12)) # одномерный массив из 12 случайных чисел от 1 до 1000
w = w.reshape((2,2,3)) # превратим w в трёхмерную матрицу
print(w)

[[[389 753 794]
  [ 67  39 463]]

 [[961 653 602]
  [972 956 708]]]


In [20]:
print(w.transpose(0,2,1))

[[[389  67]
  [753  39]
  [794 463]]

 [[961 972]
  [653 956]
  [602 708]]]


#### 1.6.7
Массив, который нужно было создать в предыдущей задаче, хранится в переменной mat. Превратите его в вертикальный вектор и напечатайте

In [58]:
mat = a
mat

array([[2, 1, 0, 0],
       [0, 2, 1, 0],
       [0, 0, 2, 1]])

In [60]:
print(mat.reshape([12,1]))

[[2]
 [1]
 [0]
 [0]
 [0]
 [2]
 [1]
 [0]
 [0]
 [0]
 [2]
 [1]]


### 1.6.8 Основные методы ndarray


In [1]:
import numpy as np

#### Базовые статистики
- a.min(axis=None), a.max(axis=None), a.mean(axis=None), a.std(axis=None) — минимум, максимум, среднее арифметическое и стандартное отклонение вдоль указанной оси. По умолчанию ось не указана и статистика считается по всему массиву. a.argmin(axis=None), a.argmax(axis=None) — индексы минимального и максимального элемента. 
Пример:
>>> print(v)
[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]
>>> print(v.mean(axis=0))  # вдоль столбцов
[ 1.  2.  3.  4.]
>>> print(v.mean(axis=1))  # вдоль строк
[ 2.5  2.5  2.5]
>>> print(v.mean(axis=None))  # вдоль всего массива
2.5


In [2]:
 v = np.array([[1, 2, 3, 4],
 [1, 2, 3, 4],
 [1, 2, 3, 4]])

In [8]:
print(v)

[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]


In [9]:
print(v.mean(axis=0))  # вдоль столбцов

[1. 2. 3. 4.]


In [10]:
print(v.mean(axis=1))  # вдоль строк

[2.5 2.5 2.5]


In [11]:
print(v.mean(axis=None))  # вдоль всего массива

2.5



Чтобы лучше понять, почему говорят «усреднение вдоль оси» — можно нарисовать эту матрицу на бумажке и прямыми линиями соединить те элементы, которые сливаются в один при усреднении. Чтобы было совсем понятно — можно ещё добавить координатные оси, чтобы каждый элемент $w_{ij}$ оказался над точкой ($i,j$).
- a.sum(axis=None), a.prod(axis=None) — сумма и произведение всех элементов вдоль указанной оси. a.cumsum(axis=None), a.cumprod(axis=None) — частичные суммы и произведения (для ($a_{1},⋯,a_{n}$) вектор частичных сумм — это ($a_{1},a_{1}+a_{2},⋯,a_{1}+⋯+a_{n}$)).

#### Линейная алгебра

Пакет
numpy.linalg
содержит большую часть стандартных операций и разложений матриц. Некоторые самые популярные функции вынесены в корень пакета NumPy.
- a.dot(b) — матричное произведение двух массивов (размерности должны быть согласованы),
linalg.matrix_power(M, n) — возведение матрицы M в степень n,
- a.T — транспонирование
- linalg.norm(a, ord=None) — норма матрицы a, по умолчанию норма Фробениуса для матриц и L2-норма для векторов; подробное описание возможных норм — в справке,
- linalg.inv(a) — матрица, обратная к a (если a необратима, выбрасывается LinAlgError; псевдообратная считается через linalg.pinv(a))

a = w.dot([1,2,3])
print(a)
[[4740 2671]
 [2552 2912]]
ainv = np.linalg.inv(a)
print(a.dot(ainv))
[[  1.00000000e+00   0.00000000e+00]
 [ -2.22044605e-16   1.00000000e+00]]

In [23]:
a = w.dot([1,2,3])
print(a)

[[4277 1534]
 [4073 5008]]


In [24]:
ainv = np.linalg.inv(a)
print(ainv)

[[ 0.0003301  -0.00010111]
 [-0.00026847  0.00028192]]


### 1.6.9 
Задача: перемножьте две матрицы!

На вход программе подаются две матрицы, каждая в следующем формате: на первой строке два целых положительных числа n и m, разделенных пробелом - $размерность \; матрицы$. В следующей строке находится $n\cdot m$ целых чисел, разделенных пробелами - элементы матрицы. Подразумевается, что матрица заполняется $построчно$, то есть первые m чисел - первый ряд матрицы, числа от $m+1$ до $2 \cdot m$ - второй, и т.д.

Напечатайте произведение матриц $XY^T$, если они имеют подходящую форму, или строку "matrix shapes do not match", если формы матриц не совпадают должным образом. 

В этот раз мы проделали за вас подготовительную работу по считыванию матриц (когда вы начнёте решать, этот код будет уже написан):

x_shape = tuple(map(int, input().split()))
X = np.fromiter(map(int, input().split()), np.int).reshape(x_shape)
 Несколько комментариев:

map(f, iterable, …) — встроенная функция языка Python, возвращает результат поэлементного применения функции f к элементам последовательности iterable; если f принимает несколько аргументов, то на вход должно быть подано соответствующее число последовательностей: результатом map(f, x, y, z) будет итератор, возвращающий поочерёдно f(x[0], y[0], z[0]), f(x[1], y[1], z[1]), f(x[2], y[2], z[2]) и так далее; результат применения f к очередному набору аргументов вычисляется только тогда, когда требуется использовать этот результат, но не ранее, подробнее и короче в справке;
np.fromiter создаёт NumPy-массив из итератора, то есть заставляет итератор вычислить все доступные значения и сохраняет их в массив;
input() — встроенная функция языка Python, читает одну строку (последовательность символов вплоть до символа переноса строки) из входного потока данных и возвращает её как строку;
split() — метод класса string, возвращает список слов в строке (здесь слова — последовательности символов, разделённые пробельными символами); принимает дополнительные аргументы, подробнее в справке.

In [29]:
x_shape = tuple(map(int, input().split()))
X = np.fromiter(map(int, input().split()), np.int).reshape(x_shape)
y_shape = tuple(map(int, input().split()))
Y = np.fromiter(map(int, input().split()), np.int).reshape(y_shape)

2 3
8 7 7 14 4 6
4 3
5 5 1 5 2 6 3 3 9 1 4 6


In [5]:
X = np.array([[8, 7, 7],
 [14, 4, 6]])
Y = np.array([[5, 5, 1],
 [5, 2, 6],
 [3, 3, 9],
 [1, 4, 6],])

In [7]:
print(X)
print(Y)
print(Y.transpose())

[[ 8  7  7]
 [14  4  6]]
[[5 5 1]
 [5 2 6]
 [3 3 9]
 [1 4 6]]
[[5 5 3 1]
 [5 2 3 4]
 [1 6 9 6]]


In [15]:
print(X.shape[1])
print(Y.shape[1])

3
3


In [17]:
if X.shape[1] == Y.shape[1]:
    print(X.dot(Y.transpose()))
else: 
    print('matrix shapes do not match')

[[ 82  96 108  78]
 [ 96 114 108  66]]


### 1.6.10 Как считать данные из файла

sbux = np.loadtxt("sbux.csv", usecols=(0,1,4), skiprows=1, delimiter=",", 

                      dtype={'names': ('date', 'open', 'close'),
                      
                             'formats': ('datetime64[D]', 'f4', 'f4')})
print(sbux[0:4])

[(datetime.date(2015, 9, 1), 53.0, 57.2599983215332)

 (datetime.date(2015, 8, 3), 58.619998931884766, 54.709999084472656)
 
 (datetime.date(2015, 7, 1), 53.86000061035156, 57.93000030517578)
 
 (datetime.date(2015, 6, 1), 51.959999084472656, 53.619998931884766)]

In [21]:
print(X)
print(X.mean(axis=0))

[[ 8  7  7]
 [14  4  6]]
[11.   5.5  6.5]


In [22]:
from urllib.request import urlopen
f = urlopen('https://stepic.org/media/attachments/lesson/16462/boston_houses.csv')

In [25]:
t = np.loadtxt(f, skiprows = 1, delimiter=",")

In [27]:
t.mean(axis=0)

array([22.50755467,  3.63495427, 11.39562624,  0.0695825 ,  0.55506899,
        6.28199602,  3.78979602])

# 1.7 Линейная алгебра в деле

- $X$ - матрица наблюдений (без целевой переменной). Условимся, что n - количество наблюдений, m - количество переменных
- $\beta$ - вектор коэффициентов. Размерность вектора $\beta$ = m + 1 * 1
- $y$ - вектор значений целевой переменной. Его размерность m * 1
- $\epsilon$ - вектор нормально распределненных ошибок. Его размерность m * 1

- $\hat{\beta}$ - вектор оценок коэффициентов
- $\hat{y}$ - вектор предсказания целевой переменной
- $\hat{\epsilon}$ - вектор ошибок предсказаний. $\hat{\epsilon} = y - \hat{y}$

### Модель линейной регрессии

$y_{i} = \sum\limits_{j=1}^m \beta_j X_{i,j} + \beta_{0} + \epsilon_{i}$

Цель построения модели - получить $\hat{\beta}$ такие, что $\sum\limits_{i=1}^n (\hat{y_{i}} - y_{i})^2 \rightarrow min$

1) $(AB)^T = B^TA^T$

2) $(1 - H)X = 0 = \\
    (1 - X(X^TX)^{-1} X^T) = \\
    X - X(X^TX)^{-1}(X^TX) = \\
    X - X = 0$
    
 

$ H = X (X^T\cdot X)^{-1}X^T$

1) $H^T = H$ - симметрична

2) $H \cdot H = H $ - идемпотентна

$Q = \hat\epsilon^T \epsilon = (y - X\hat\beta)^T(y - X\hat\beta)$

$h = Hy + (1 - H)y$

$Q = (Hy + (1 - H)y - X\hat\beta)^T(Hy + (1 - H)y - X\hat\beta) = \\
= (Hy - X\hat\beta + (1 - H)y )^T(Hy - X\hat\beta + (1 - H)y ) = \\
= ((Hy - X\hat\beta )^T + ((1 - H)y)^T)((Hy - X\hat\beta) + ((1 - H)y)) = \\
= (Hy - X\hat\beta )^T(Hy - X\hat\beta) + (Hy - X\hat\beta )^T((1 - H)y) + 
  ((1 - H)y)^T (Hy - X\hat\beta ) + ((1 - H)y)^T((1 - H)y) = \\
= (Hy - X\hat\beta )^T(Hy - X\hat\beta) + ((1 - H)y)^T((1 - H)y) = \\
= ((1 - H)y)^T((1 - H)y)
$

### 1.7.12 

Теперь давайте попробуем применить наши новые матричные формулы — сначала на игрушечном примере, который мы рассматривали пару видео назад.

У нас есть набор данных: знания о длине тормозного пути и скорости для трёх автомобилей.

$ \left[ 
    \begin{array}{ccc}
    D \; V \\ 
    10 \; 60  \\
    7 \;50  \\
    12 \; 75 \\
    \end{array}
\right] $


Напишите через запятую оценки коэффициентов линейной регрессии D на V, т.е. β^0, β^1 для модели $D=β_0+β_1V+ε$ с точностью до трёх знаков после точки.


In [2]:
import numpy as np

In [3]:
# матрица
matr = np.array([[10, 60],
              [7, 50],
              [12, 75]])

In [4]:
# столбец единиц
ones = np.ones([3, 1])
ones

array([[1.],
       [1.],
       [1.]])

In [17]:
# Объединить матрицы по-горизонтали, убрать последний столбец
X = np.hstack((ones, matr[:, 1].reshape(3,1)))
print(X)
y = matr[:, 0]
print(y)

[[ 1. 60.]
 [ 1. 50.]
 [ 1. 75.]]
[10  7 12]


In [25]:
step1 = X.T.dot(X)
step1

array([[3.0000e+00, 1.8500e+02],
       [1.8500e+02, 1.1725e+04]])

In [21]:
step2 = np.linalg.inv(step1) # np.linalg.inv(step1)
step2

array([[ 1.23421053e+01, -1.94736842e-01],
       [-1.94736842e-01,  3.15789474e-03]])

In [22]:
step3 = step2.dot(X.T)
step3

array([[ 0.65789474,  2.60526316, -2.26315789],
       [-0.00526316, -0.03684211,  0.04210526]])

In [23]:
b = step3.dot(y)
b

array([-2.34210526,  0.19473684])

### 1.7.13 

$\hat\beta = (X^T\cdot X)^{-1}X^Ty$ 

$ H = X (X^T\cdot X)^{-1}X^T$

$\hat y = X\hat\beta = Hy$





### 1.7.15

Найдите оптимальные коэффициенты для построения линейной регрессии.

На вход вашему решению будет подано название csv-файла, из которого нужно считать данные. Пример можно посмотреть здесь. Загрузить их можно следующим образом:

fname = input()  # read file name from stdin
f = urllib.request.urlopen(fname)  # open file from URL
data = np.loadtxt(f, delimiter=',', skiprows=1)  # load data to work with
Ваша задача — подсчитать вектор коэффициентов линейной регрессии для предсказания первой переменной (первого столбца данных) по всем остальным. Напомним, что модель линейной регрессии — это y=β0+β1x1+⋯+βnxn.

Напечатайте коэффициенты линейной регрессии, начиная с β0, через пробел. Мы будем проверять совпадения с точностью до 4 знаков после запятой.

Методы и приёмы, которые мы ещё не упоминали и которые могут вам помочь в процессе решения (могут являться подсказками!):

np.hstack((array1, array2, ...))  # склеивает по строкам массивы, являющиеся компонентами кортежа, поданного на вход; массивы должны совпадать по всем измерениям, кроме второго
np.ones_like(array)  # создаёт массив, состоящий из единиц, идентичный по форме массиву array
"delim".join(array)  # возвращает строку, состоящую из элементов array, разделённых символами "delim"
map(str, array)  # применяет функцию str к каждому элементу array

Sample Input:

https://stepic.org/media/attachments/lesson/16462/boston_houses.csv
Sample Output:

-3.65580428507 -0.216395502369 0.0737305981755 4.41245057691 -25.4684487841 7.14320155075 -1.30108767765


In [26]:
import urllib
from urllib import request
import numpy as np


In [27]:
fname = 'https://stepic.org/media/attachments/lesson/16462/boston_houses.csv'

In [28]:
#fname = input()  # read file name from stdin
f = urllib.request.urlopen(fname)  # open file from URL
data = np.loadtxt(f, delimiter=',', skiprows=1)  # load data to work with


In [35]:
data

array([[2.4000e+01, 6.3200e-03, 1.8000e+01, ..., 5.3800e-01, 6.5750e+00,
        4.0900e+00],
       [2.1600e+01, 2.7310e-02, 0.0000e+00, ..., 4.6900e-01, 6.4210e+00,
        4.9671e+00],
       [3.4700e+01, 2.7290e-02, 0.0000e+00, ..., 4.6900e-01, 7.1850e+00,
        4.9671e+00],
       ...,
       [2.3900e+01, 6.0760e-02, 0.0000e+00, ..., 5.7300e-01, 6.9760e+00,
        2.1675e+00],
       [2.2000e+01, 1.0959e-01, 0.0000e+00, ..., 5.7300e-01, 6.7940e+00,
        2.3889e+00],
       [1.1900e+01, 4.7410e-02, 0.0000e+00, ..., 5.7300e-01, 6.0300e+00,
        2.5050e+00]])

In [39]:
data 

array([[2.4000e+01, 6.3200e-03, 1.8000e+01, ..., 5.3800e-01, 6.5750e+00,
        4.0900e+00],
       [2.1600e+01, 2.7310e-02, 0.0000e+00, ..., 4.6900e-01, 6.4210e+00,
        4.9671e+00],
       [3.4700e+01, 2.7290e-02, 0.0000e+00, ..., 4.6900e-01, 7.1850e+00,
        4.9671e+00],
       ...,
       [2.3900e+01, 6.0760e-02, 0.0000e+00, ..., 5.7300e-01, 6.9760e+00,
        2.1675e+00],
       [2.2000e+01, 1.0959e-01, 0.0000e+00, ..., 5.7300e-01, 6.7940e+00,
        2.3889e+00],
       [1.1900e+01, 4.7410e-02, 0.0000e+00, ..., 5.7300e-01, 6.0300e+00,
        2.5050e+00]])

In [74]:
data[:, 1:]

array([[6.3200e-03, 1.8000e+01, 0.0000e+00, 5.3800e-01, 6.5750e+00,
        4.0900e+00],
       [2.7310e-02, 0.0000e+00, 0.0000e+00, 4.6900e-01, 6.4210e+00,
        4.9671e+00],
       [2.7290e-02, 0.0000e+00, 0.0000e+00, 4.6900e-01, 7.1850e+00,
        4.9671e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 0.0000e+00, 5.7300e-01, 6.9760e+00,
        2.1675e+00],
       [1.0959e-01, 0.0000e+00, 0.0000e+00, 5.7300e-01, 6.7940e+00,
        2.3889e+00],
       [4.7410e-02, 0.0000e+00, 0.0000e+00, 5.7300e-01, 6.0300e+00,
        2.5050e+00]])

In [81]:
ones = np.ones([np.shape(data)[0], 1])

In [80]:
np.shape(ones)

(506, 1)

In [79]:
np.shape(data[:, 1:])

(506, 6)

In [87]:
X = np.hstack((ones, data[:, 1:].reshape(np.shape(data)[0], np.shape(data)[1] - 1)))

In [90]:
y = data[:, 0]

In [91]:
X_t_X = X.transpose().dot(X)

In [92]:
inv_X_t_X = np.linalg.inv(X_t_X)

In [93]:
inv_X_t_X_X_t = inv_X_t_X.dot(X.T)

In [94]:
beta = inv_X_t_X_X_t.dot(y)

In [95]:
print(' '.join(list(map(str, beta))))

-3.6558042850625045 -0.2163955023691484 0.07373059817548466 4.412450576912816 -25.468448784099316 7.143201550746264 -1.3010876776490106


## 2.1 Нейроны

Нейропластичность - способность нейронов учитывать опыт предыдущих периодов.
Rewiring experiment - эксперимент с перепроводкой путей поступления информации.
Сенсорное замещение - использование одного анализатора для сбора информации, обычно получаемого через другой сенсорный орган 


## 2.2 Перцептрон

- Модель была предложена и популяризована Ф. Розенблатом, в начале 1960-х. 
- В 1969 году Мински и Паперт (M.Minsky, S.Papert Perceptrons: an introduction to computational geometry.) в которой рассматривали ограничения перцепртрона. 
- AI winter 1974-1980 - период спада интереса к технологиям искусственного интеллекта
- На сегодняшний день перцептроны используются в задачах с большим числом предикторов.

На первичном уровне перцептрон представляет собой искусственный нейрон. У него есть входы и веса, на основании которых формируется выход.
Поведение перцептрона можно описать следующей функцией трех аргументов:

$$
f(x, w, b) = 
\left\{
    \begin{matrix}
    1, если \sum\limits_{i=1}^m w_i \cdot x_i + b > 0 \\
    0 \; иначе
    \end{matrix} \right.
$$

где w - вектор весов, x - вектор входных активаций, b - смещение (bias), а f(w, x, b) - выходная активация перцептрона.

Если сумма попарных произведений соответствующих элементов весов и активаций плюс смещение превышает ноль, то перцептрон выдает 1.

Если перенести смещение в другую часть неравенства, то получим порог t. Если сумма входов, с учетом важности этих входов превысит порог t, то нейрон активируется.

Активационная функция заключается в сравнении с нулем (фукнция Хевисайда (НЕТ))

Первый вход фиктивный. На него всегда будет подаваться единица. Этот вход и будет смещением (bias).

$b = w_0$

Теперь можно записать перцептрон следующим образом. Смещения уже нет. Функция равна 1, если скалярное прозиведение весов и входов больше ноля и 0 в остальных случаях 

$
f(x, w, b) = 
\left\{
    \begin{matrix}
    1, w^T x > 0 \\
    0 \; w^T x <= 0
    \end{matrix} \right.
$





$
\begin{equation}
    \begin{matrix}
    \hat{\Phi}[k,l] & =
    & \left\{
    \begin{matrix}
    0 & \mbox{if } k,l = 0 \\
    S_x[k,l]\cdot H_x[k,l] + S_y[k,l]\cdot H_y[k,l] & \mbox{otherwise }
    \end{matrix} \right.
    \end{matrix}
\end{equation}[
$

$ \left[ 
    \begin{array}{ccc}
    x_{1}c \\ 
    x_{2}c  \\
    ..  \\
    x_{n}c \\
    \end{array}
\right] $

$
\begin{equation}
    \begin{matrix}
    \hat{\Phi}[k,l] & =
    & \left\{
    \begin{matrix}
    0 & \mbox{if } k,l = 0 \\
    S_x[k,l]\cdot H_x[k,l] + S_y[k,l]\cdot H_y[k,l] & \mbox{otherwise }
    \end{matrix} \right.
    \end{matrix}
\end{equation}[
$

## 2.3.1 Перцептрон. Обучение

In [1]:
import numpy as np
# Функция И
X=np.array([[0,0],
            [1,0],
            [0,1],
            [1,1]])
Y=np.array([0,0,0,1])
W=np.array([0,0])

def Predict(X,W):
    return np.dot(X,W)

perfect=False
while not(perfect):
    perfect=True
    if not((Predict(X,W) == Y).all()):
        e=np.where((Predict(X,W) == Y)==False)[0][0]
        if Y[e]==1:
            W+=X[e][:]
        else:
            W-=X[e][:]

print(W)

[1 1]


$\Delta w_i=(y−\hat y)⋅x_i$

### 2.3.3 Перцептрон: обучение

Мы погуляли в фруктовом саду и собрали следующие данные про несколько обнаруженных там фруктов:

    желтизна    симметричность   это груша
1   1           0.3              да
2   0.4         0.5              да
3   0,7         0.8              нет

Пусть у нас есть перцептрон с весами (0, 0) и смещением 0. 

Обучите его на приведённых данных различать груши и не груши (пока не надо обучать до сходимости: просто примените обучающее правило последовательно по одному разу на каждом примере, всего у вас получится 3 последовательных применения обучающего правила). 

Напишите в ответе через запятую получившиеся у вас смещение, вес для желтизны фрукта и вес для его симметричности (только итоговые, не надо писать результаты каждого шага).



In [5]:
# Функция И
import numpy as np

X = np.array([[1, 1, 0.3],
            [1, 0.4, 0.5],
            [1, 0.7, 0.8]])
Y = np.array([1, 1, 0])
W = np.array([0, 0, 0])

def Predict(X, W):
    return np.dot(X, W)

perfect = False
while not(perfect):
    perfect = True
    if not((Predict(X, W) == Y).all()):
        e = np.where((Predict(X, W) == Y)==False)[0][0]
        if Y[e] == 1:
            W += X[e][:]
        else:
            W -= X[e][:]

print(W)

TypeError: Cannot cast ufunc add output from dtype('float64') to dtype('int32') with casting rule 'same_kind'

In [6]:
X = np.array([[1, 1, 0.3],
            [1, 0.4, 0.5],
            [1, 0.7, 0.8]])
Y = np.array([1, 1, 0])
W = np.array([0, 0, 0])

def Predict(X, W):
    return np.dot(X, W)

perfect = False

In [7]:
perfect = True

In [11]:
(Predict(X, W) == Y)

array([False, False,  True])

In [14]:
np.where((Predict(X, W) == Y)==False)

(array([0, 1], dtype=int64),)

In [21]:
Predict(X, W) == Y

array([False, False,  True])

In [22]:
np.where((Predict(X, W) == Y)==False)

(array([0, 1], dtype=int64),)

In [17]:
e = np.where((Predict(X, W) == Y)==False)[0][0]

In [18]:
e

0

In [19]:
X[e][:]

array([1. , 1. , 0.3])

In [ ]:

if not((Predict(X, W) == Y).all()):
    e = np.where((Predict(X, W) == Y)==False)[0][0]
    if Y[e] == 1:
        W += X[e][:]
    else:
        W -= X[e][:]

In [23]:
#
import numpy as np

w = np.array([[0, 0, 0]])
print("w shape", w.shape)

examples = np.array([[1, 1, 0.3], 
                     [1, 0.4, 0.5],
                    [1, 0.7, 0.8]])

def target(ex):
    if ex[1] == 1 and ex[2] == 0.3:
        return 1
    elif ex[1] == 0.4 and ex[2] == 0.5:
        return 1
    elif ex[1] == 0.7 and ex[2] == 0.8:
        return 0
    
def predict(example):
    sum = example[0] * w[0][0] + example[1] * w[0][1] + example[2] * w[0][2]
    # sum = w.dot(example)
    print("example ", example)
    print("sum ", sum)
    if sum > 0:
        return 1
    else:
        return 0

iteration = 0
perfect = False
while not perfect:
    print('iteration: ', iteration)
    perfect = True
    for e in examples:
        print("e", e)
        if predict(e) != target(e):
            perfect = False
            if predict(e) == 0:
                w = w + e
                print("w ", 2)
            else:
                w = w - e
                print("w ", w)
    iteration += 1

print("final answer ", w)

w shape (1, 3)
iteration:  0
e [1.  1.  0.3]
example  [1.  1.  0.3]
sum  0.0
example  [1.  1.  0.3]
sum  0.0
w  2
e [1.  0.4 0.5]
example  [1.  0.4 0.5]
sum  1.5499999999999998
e [1.  0.7 0.8]
example  [1.  0.7 0.8]
sum  1.94
example  [1.  0.7 0.8]
sum  1.94
w  [[ 0.   0.3 -0.5]]
iteration:  1
e [1.  1.  0.3]
example  [1.  1.  0.3]
sum  0.15000000000000005
e [1.  0.4 0.5]
example  [1.  0.4 0.5]
sum  -0.12999999999999998
example  [1.  0.4 0.5]
sum  -0.12999999999999998
w  2
e [1.  0.7 0.8]
example  [1.  0.7 0.8]
sum  1.49
example  [1.  0.7 0.8]
sum  1.49
w  [[ 0.00000000e+00  1.11022302e-16 -8.00000000e-01]]
iteration:  2
e [1.  1.  0.3]
example  [1.  1.  0.3]
sum  -0.23999999999999988
example  [1.  1.  0.3]
sum  -0.23999999999999988
w  2
e [1.  0.4 0.5]
example  [1.  0.4 0.5]
sum  1.15
e [1.  0.7 0.8]
example  [1.  0.7 0.8]
sum  1.2999999999999998
example  [1.  0.7 0.8]
sum  1.2999999999999998
w  [[ 0.   0.3 -1.3]]
iteration:  3
e [1.  1.  0.3]
example  [1.  1.  0.3]
sum  -0.0899999999

import numpy as np
Y = np.array([1,1,0]) #реальные ответы
X = np.array([[1, 1, 0.3, 0],
              [1, 0.4, 0.5, 0],
              [1, 0.7, 0.8, 0]]) #массив значений
X[:,3] = Y.transpose() #подтягиваем ответы в массив значений
w = np.array([0,0,0]) #массив весов
def Predict(X):
    E = X.dot(w.transpose()) #сумматор
    p = 1 if E > 0 else 0 #активатор
    return p
perfect = False
while perfect == False:
    perfect = True
    for ex in X:
        #сравниваем предсказание с реальным ответом
        if Predict(ex[0:3]) != ex[3]:
            perfect = False
            #если ответ не совпадает, правим веса
            w = w + (ex[3] - Predict(ex[0:3]))*ex[0:3]
print(w)

In [ ]:
import numpy as np
X=np.array([[1, 1, 0.3, 1],
              [1, 0.4, 0.5, 1],
              [1, 0.7, 0.8, 0]]) #массив значений
W=np.array([0,0,0]) #массив весов
while True:
    for ex in X:
        d=ex[3]-(ex[0:3]@ W.T>0)
        W=W+d*ex[0:3]*abs(d)
    if not d: break
print(W)

## 2.3.4

Если существует набор весов, который решает проблему, то этот набор весов будет найдет за конечное время.



## 2.4.11 Нейроны ReLU и softplus

### Rectified linear unit (RelU)

$$f(x, w, b) = max(w \cdot x + b, 0)$$

$f(x, w, b) $ - выходная активация нейрона

$x$ - вектор входных активаций

$w$ - вектор весов

$b$ - смещение (bias)

$max(a,b)$ - максимум из двух элементов


### Softplus (Аналитическое приближение ReLU)

$$f(x, w, b) = ln(1 + e^{x \cdot w + b})$$

$f(x, w, b) $ - выходная активация нейрона

$x$ - вектор входных активаций

$w$ - вектор весов

$b$ - смещение (bias)

$ln(1 + e^t)$ - softplus функция (по определению)



# 2.5 Градиентный спуск

## 2.5.1 Квадратичная целевая функция

$$J = \frac{1}{2} \sum\limits_{i=1}^n (\hat y^{(i)} - y^{(i)})^n $$

$\hat y^{(i)}$ - предсказываемое значение

$y^{(i)}$ - реальное значение

$\hat y$ - какой-то вектор

$\hat y^{(i)}$ - какой-то элемент вектора $\hat y$

Целевая функция - мера насколько хорошо ведет себя алгоритм, как хорошо он может справляться с данными.

Квадратичния функция потерь не единственный вариант.

Функцией потерь (Loss function) - называются потери на одном конкретном примере. 
В данном случае Loss function это $(\hat y^{(i)} - y^{(i)})^2$.

оно же Cost function .

Целевая функция - это то что комбинирует отдельные значения функции потерь для различных примеров в какое-то одно число. Таким образом мы получаем меру успешности поведения нашего алгоритма на наших данных.

Целевая функция показывает как сильно ошибалась наша модель. Значит нужно ее минимизировать. 



## 2.5.7 Метод градиентного спуска

Градиентной функцией называется вектор, составленный из частных производных этой функции по каждой из ее аргументов

Градиент функции J

$$ \nabla J = 
\left[
\begin{array}{ccc}
\frac{\partial J}{\partial w_1}   \\
..   \\
\frac{\partial J}{\partial w_m}   \\
\end{array}
\right]
$$

Градиент связан с приращением функции.

$$ \nabla J = 
\left[
\begin{array}{ccc}
\frac{\partial J}{\partial w_1}   \\
\frac{\partial J}{\partial w_2}   \\
\end{array}
\right]
=
\left[
\begin{array}{ccc}
1   \\
1.2   \\
\end{array}
\right]
$$

Вектор $\nabla J$ - направление наибольшего роста функции.


## 2.5.11 Алгоритм обучения

Сначала вычисляем значение градиента в определенной точке.
Домножаем значение этого градиента на -1, чтобы получить направление наискорейшего спуска
Домножаем то что получилось на некоторую константу ($\alpha$). Константу скорости обучения (learning rate). Она влияет на величину шагов, которые мы будем совершать.
Взяли то что получилось и прибавили к тем весам, которые у нас были. Таким образом, получаем веса, которые у нас будут на следущем шаге алгоритма. 

$\varepsilon $ - максимальное значение градиента, при котором считаем, что цель достигнута.







$\sum\limits_{i=1}^n (\hat{y_{i}} - y_{i})^2 \rightarrow min$

$\mathrm{grad}\,\varphi = \nabla \varphi = \frac {\partial \varphi} {\partial x} \vec e_x + \frac {\partial \varphi} {\partial y} \vec e_y + \frac {\partial \varphi} {\partial z} \vec e_z. $

Сначала посмотрим, как можно получить градиент, когда у нас целевая функция квадратичная и мы решаем задачу регрессии. Будет использоваться линейный нейрон
Во втором случае посмотрим задачу классификации. Будет использоваться сигмоидальный нейрон.

Важно: Использовать квадратичную целевую функцию для задачи классификации, не лучшая идея. Это сделано для того чтобы было легче.
Важно: Градиентный спуск - это краеугольный камень всего дальнейшего курса.

##### Вывод правила обучения для линейного нейрона.

Мы собираемся вычислять градиент для случая, когда мы решаем задачу регрессии с помощью линейного нейрона и используя квадратичную функцию потерь.

$$J = \frac{1}{2} \sum\limits_{i=1}^n (\hat y^{(i)} - y^{(i)})^2 $$


$w^t$  - вектор весов

$x$  - вектор входных активаций 

Линейный нейрон выглядит следующим образом $\hat y^{(i)} = w^t x^{(i)}$, при условии что в векторе весов $w^t$ уже хранится базис, первый элемент $x$ всегда единица, тогда получается, что активация линейного нейрона.




In [ ]:
##### 2.6.5

x.shape=(n,m) , w.shape=(m,1)
x.shape=(m,n) , w.shape=(m,1)
x.shape=(m,n) , w.shape=(1,m)
x.shape=(n,m), w.shape=(1,m)

w.T.dot(x).T
x.dot(w.T)
x.dot(w)
w.dot(x).T

In [14]:
import numpy as np
import random

In [18]:
n = 2
m = 3

In [25]:
x = np.array(random.sample(range(9), 6)) # одномерный массив из 12 случайных чисел от 1 до 1000
w = np.array(random.sample(range(9), m))

In [27]:
#1 x.shape=(n,m), w.shape=(m,1)
x = x.reshape((n, m)) 
w = w.reshape((m, 1))
print(x)
print(w)

[[1 0 6]
 [5 3 8]]
[[6]
 [2]
 [4]]


In [30]:
x.dot(w)

array([[30],
       [68]])

In [32]:
#2 x.shape=(m,n) , w.shape=(m,1)
x = x.reshape((m, n)) 
w = w.reshape((m, 1))
print(x)
print(w)

[[1 0]
 [6 5]
 [3 8]]
[[6]
 [2]
 [4]]


In [36]:
w.T.dot(x).T

array([[30],
       [42]])

In [37]:
#3 x.shape=(m,n), w.shape=(1,m)
x = x.reshape((m, n)) 
w = w.reshape((1, m))
print(x)
print(w)

[[1 0]
 [6 5]
 [3 8]]
[[6 2 4]]


In [39]:
w.dot(x).T

array([[30],
       [42]])

In [40]:
#4 x.shape=(n,m), w.shape=(1,m)
x = x.reshape((n, m)) 
w = w.reshape((1, m))
print(x)
print(w)

[[1 0 6]
 [5 3 8]]
[[6 2 4]]


In [41]:
x.dot(w.T)

array([[30],
       [68]])

##### Вывод правила обучения для линейного нейрона.


$$ \nabla J = 
\left[
\begin{array}{ccc}
..   \\
\frac{\partial J}{\partial w_1}   \\
..   \\
\end{array}
\right]
$$


